In [1]:
import numpy as np

In [2]:
sample_data = np.array([1., 2., 3.])

In [3]:
sample_data.dtype

dtype('float64')

In [4]:
sample_data.size

3

In [5]:
sample_data.shape

(3,)

In [7]:
sample_data.ndim

1

In [11]:
sample_data.itemsize

8

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.empty((2,3,4))

array([[[4.66308601e-310, 0.00000000e+000, 6.91400352e-310,
         6.91400352e-310],
        [6.91400351e-310, 6.91400352e-310, 6.91400351e-310,
         6.91400352e-310],
        [6.91400351e-310, 6.91400352e-310, 6.91400351e-310,
         6.91400352e-310]],

       [[6.91400352e-310, 6.91400351e-310, 6.91400351e-310,
         6.91400352e-310],
        [6.91400351e-310, 6.91400352e-310, 6.91400351e-310,
         6.91400351e-310],
        [6.91400351e-310, 6.91400351e-310, 6.91400351e-310,
         6.91400352e-310]]])

In [16]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [17]:
from numpy import pi

In [18]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [19]:
np.linspace(0, 2*pi, 100)

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [20]:
np.arange(10, 30, 10)

array([10, 20])

In [21]:
x = np.linspace(0, 2*pi, 100)
f = np.sin(x)