In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2], [3,4]]
x_data = torch.Tensor(data)

In [3]:
### numpy array to tensor

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [ ]:
### Creating tensor, retaining shape and type only

In [6]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1., 1.],
        [1., 1.]]) 



In [7]:
x_rand = torch.rand_like(x_data, dtype=torch.float) # overriding the type
print(f"Random Tensor \n {x_rand} \n")

Random Tensor 
 tensor([[0.0740, 0.6317],
        [0.6335, 0.0965]]) 



In [8]:
### From shape tuple
shape = (2,3)

In [9]:
rand_tensor = torch.rand(shape)
one_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [10]:
### Attributes of a tensor

In [13]:
tensor = torch.rand(3,4) # returns a randomly generated 3x4 tensor

In [14]:
print(f"Shape of tensor : {tensor.shape}")
print(f"Datatype of tensor : {tensor.dtype}")
print(f"Device tensor is stored in: {tensor.device}")

Shape of tensor : torch.Size([3, 4])
Datatype of tensor : torch.float32
Device tensor is stored in: cpu


In [15]:
## Checking if gpu is available and switching
device = "cuda" if torch.cuda.is_available() else "cpu"

In [18]:
print(device)

cuda


In [19]:
tensor = torch.rand(3,4).to(device)

In [ ]:
### Alternate way
with tensor.cuda.is_available():
    tensor = tensor.to("cuda")

In [20]:
print(f"Shape of tensor : {tensor.shape}")
print(f"Datatype of tensor : {tensor.dtype}")
print(f"Device tensor is stored in: {tensor.device}")

Shape of tensor : torch.Size([3, 4])
Datatype of tensor : torch.float32
Device tensor is stored in: cuda:0


In [21]:
### Tensor operations

In [22]:
tensor = torch.ones(3,4)

In [23]:
print(f"First row : {tensor[0]}")

First row : tensor([1., 1., 1., 1.])


In [24]:
print(f"First column : {tensor[:,0]}")

First column : tensor([1., 1., 1.])


In [25]:
print(f"Last Column : {tensor[:-1]}")

Last Column : tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [26]:
#setting the 2nd column to all 0
tensor[:,1] = 0

In [27]:
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### Joining tensors

In [28]:
t1 = torch.cat([tensor, tensor, tensor])

### Arithmetic using tensor

In [29]:
### Matrix mul of two tensors
# [3*4] x [4*3] => [3 * 3]
y1 = tensor @ tensor.T

In [30]:
y1

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [31]:
y2 = tensor.matmul(tensor.T)

In [32]:
y2

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [33]:
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [34]:
y3

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [35]:
### Element-wise product

In [42]:
z1 = tensor * tensor #[note: they both need to be same shape]
z2 = tensor.mul(tensor)
assert((z1 == z2).sum().item() / (z2.shape[1] * z2.shape[0]) == 1)

In [43]:
### Tensor in-place operations

In [45]:
print(f"{tensor} \n")
tensor.add_(5)      
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [ ]:
### Tensor to numpy

In [46]:
n_a = tensor.numpy()
print(type(n_a))

<class 'numpy.ndarray'>
